config/routes.rb
Rails.application.routes.draw do
  get '/services', to: 'services#index', as: :services
  get '/:from/:to/:day/:time.json', to: 'services#json', as: :services_json
  get '/:from/:to/:day/:time', to: 'services#show', as: :service
  get '/', to: 'pages#home'
end

app/models/service.rb
class Service
  class ApiError < StandardError; end

  def self.services(from, to, date, time)
    if time == '00:00'
      from_offset = 'PT00:00:00'
    else
      from_offset = '-PT01:00:00'
    end

    if time == '23:00'
      to_offset = 'PT00:59:00'
    else
      to_offset = 'PT01:00:00'
    end

    params = {
      app_id: ENV['app_id'],
      app_key: ENV['app_key'],
      calling_at: to,
      from_offset: from_offset,
      to_offset: to_offset,
      station_detail: 'calling_at',
      train_status: 'passenger'
    }

    url = "https://transportapi.com/v3/uk/train/station/#{from}/#{date}/#{time}/timetable.json?#{params.to_query}"

    redis = Redis.new

    if redis.exists(url)
      body = redis.get(url)
    else
      body = Faraday.get(url).body
      redis.set(url, body)
      body
    end

    result = JSON.parse(body)

    Rails.logger.debug(url)
    Rails.logger.debug(JSON.pretty_generate(result))

    if result['error']
      raise ApiError.new(result['error'])
    else
      result['departures']['all'].map{|attributes| new(from, to, date, attributes) }.select(&:has_arrival_time?)
    end
  end

  attr_reader :from, :to

  def initialize(from, to, date, attributes)
    @from = from
    @to = to
    @date = Date.parse(date)
    @attributes = attributes
  end

  def new_timetable?
    @date >= Date.parse('2019-05-19')
  end

  def departure_datetime
    Time.zone.parse("#{@date} #{departure_time}")
  end

  def has_arrival_time?
    arrival_time.present?
  end

  def arrival_datetime
    if departure_time < arrival_time
      Time.zone.parse("#{@date} #{arrival_time}")
    else
      Time.zone.parse("#{@date + 1.day} #{arrival_time}")
    end
  end

  def departure_time
    @attributes['aimed_departure_time']
  end

  def arrival_time
    @attributes['station_detail']['calling_at'].last['aimed_arrival_time']
  end

  def overtaken?(services)
    services.any? {|service|
      service.new_timetable? == new_timetable? &&
      service != self &&
      service.departure_datetime > departure_datetime &&
      service.arrival_datetime < arrival_datetime
    }
  end

  def length
    ((arrival_datetime - departure_datetime) / 60).round
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @use_image = true
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    from = params.fetch(:from, '').upcase.strip
    to = params.fetch(:to, '').upcase.strip
    if from.length != 3 || to.length != 3
      flash[:alert] = view_context.safe_join([
        "Please use 3-letter station codes.",
        view_context.tag('br'),
        view_context.link_to("You can look up codes on National Rail", "http://www.nationalrail.co.uk/stations_destinations/default.aspx"),
        '.'
      ])
      render 'pages/home'
    else
      redirect_to service_path(from, to, params[:day], params[:time])
    end
  end

  def show
  end

  def json
    @services = Service.services(params[:from], params[:to], old_date, params[:time])
    @services += Service.services(params[:from], params[:to], new_date, params[:time])

    stations = [
      {name: params[:from], distance: 0},
      {name: params[:to], distance: 50}
    ]

    if params[:from] == 'KGX'
      @services += Service.services('STP', params[:to], old_date, params[:time])
      @services += Service.services('STP', params[:to], new_date, params[:time])
      stations << {name: 'STP', distance: 5}
    elsif params[:to] == 'KGX'
      @services += Service.services(params[:from], 'STP', old_date, params[:time])
      @services += Service.services(params[:from], 'STP', new_date, params[:time])
      stations << {name: 'STP', distance: 55}
    end

    start_time = @services.map(&:departure_time).min
    end_time = @services.map(&:arrival_time).max

    data = {
      current_start: Time.zone.parse("#{old_date} #{start_time}"),
      current_end: Time.zone.parse("#{old_date} #{end_time}"),
      new_start: Time.zone.parse("#{new_date} #{start_time}"),
      new_end: Time.zone.parse("#{new_date} #{end_time}"),
      stations: stations,
      services: @services.map{|service|
        {
          from: service.from,
          departure: service.departure_datetime,
          to: service.to,
          arrival: service.arrival_datetime,
          overtaken: service.overtaken?(@services),
          new_timetable: service.new_timetable?,
          length: service.length
        }
      }
    };

    render json: data
  rescue Service::ApiError
    render json: {error: true}
  end

  DATES = {
    'weekday' => ['2019-05-13', '2019-05-20'],
    'saturday' => ['2019-05-11', '2019-05-25'],
    'sunday' => ['2019-05-12', '2019-05-26']
  }

  def old_date
    DATES[params[:day].downcase].first
  end
  helper_method :old_date

  def new_date
    DATES[params[:day].downcase].second
  end
  helper_method :new_date
end

app/helpers/application_helper.rb
module ApplicationHelper

  def times_for_select
    options_for_select([
      ['12am', '00:00'],
      ['1am', '01:00'],
      ['2am', '02:00'],
      ['3am', '03:00'],
      ['4am', '04:00'],
      ['5am', '05:00'],
      ['6am', '06:00'],
      ['7am', '07:00'],
      ['8am', '08:00'],
      ['9am', '09:00'],
      ['10am', '10:00'],
      ['11am', '11:00'],
      ['12pm', '12:00'],
      ['1pm', '13:00'],
      ['2pm', '14:00'],
      ['3pm', '15:00'],
      ['4pm', '16:00'],
      ['5pm', '17:00'],
      ['6pm', '18:00'],
      ['7pm', '19:00'],
      ['8pm', '20:00'],
      ['9pm', '21:00'],
      ['10pm', '22:00'],
      ['11pm', '23:00']
    ], params[:time] || '08:00')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetable Changes</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-18262427-2"></script>
    <%- if @use_image -%>
      <link rel="img_src" href="<%= asset_path('example.png') %>" />
    <%- end -%>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-18262427-2');
    </script>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <footer>
      <a href="https://chriszetter.com/blog/2018/05/11/visualizing-changes-to-rail-services/">Read more about this tool and Marey-style charts</a>.<br/>
      Train times supplied by <a href="https://www.transportapi.com/">transportapi</a>, code available <a href="https://github.com/zetter/timetable-changes">on Github</a>.<br/>
      If something looks wrong, please <a href="https://twitter.com/czetter">let me know</a>. This is a toy project, if you’re planning a journey please check times on a <a href="http://www.nationalrail.co.uk/">real website</a>.
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Timetable Changes</h1>
<p>
  This tool helps to compare the current and new services for the May 2019 timetable change.
</p>

<% if flash[:alert] %>
  <div class="alert">
    <%= flash.discard[:alert] %>
  </div>
<% end %>

<form action="<%= services_path %>" method="get">
  I am going from
  <%= text_field_tag(:from, params[:from], size: 5, placeholder: "HIT") %>
  to
  <%= text_field_tag(:to, params[:to], size: 5,  placeholder: "KGX") %>
  on
  <%= select_tag("day", options_for_select([['a weekday', 'weekday'], ['Saturday', 'saturday'], ['Sunday', 'sunday']], params[:day] || 'weekday')) %>
  at around
  <%= select_tag("time", times_for_select) %>
  <div class="submit-wrapper">
    <%= submit_tag '🚂 Show me the trains', class: 'btn' %>
  </div>
</form>

<h2>Some examples:</h2>
<ul>
  <li><a href="/HIT/KGX/weekday/07:00">Hitchin to Kings Cross at 7am on a Weekday</a></li>
  <li><a href="/FPK/LET/saturday/10:00">Finsbury Park to Letchworth Garden City at 10am a Saturday</a></li>
  <li><a href="/KGX/SNO/weekday/21:00">Kings cross to St Neots at 9pm on a Weekday</a></li>
<ul>

app/views/services/index.html.erb
<script src="//d3js.org/d3.v3.min.js"></script>

<div class="chart-container" data-url="<%= services_json_path(params[:from], params[:to], params[:time]) %>">
</div>

app/views/services/show.html.erb
<form action="<%= services_path %>" method="get">
  Showing services from
  <%= text_field_tag(:from, params[:from], size: 5, placeholder: "HIT") %>
  to
  <%= text_field_tag(:to, params[:to], size: 5,  placeholder: "KGX") %>
  on
  <%= select_tag("day", options_for_select([['a weekday', 'weekday'], 'Saturday', 'Sunday'], params[:day] || 'weekday')) %>
  at around
  <%= select_tag("time", times_for_select) %>
  <%= submit_tag '🚂 Show me different trains', class: 'btn' %>
</form>

<div class="loading">
  Loading...
</div>

<div class="chart-container" data-url="<%= services_json_path(params[:from], params[:to], params[:day], params[:time]) %>">
</div>

<p class="comparing">Comparing current services on <%= old_date %> to new services on <%= new_date %>.<br>
Services may not show if there's planned engineering work.</p></p>

<script src="//d3js.org/d3.v3.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.1/moment.min.js"></script>